# Generated by Django 3.0.5 on 2020-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200415_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_name',
            field=models.CharField(max_length=20, null=True, verbose_name='子名称'),
        ),
    ]
