# Generated by Django 3.0.5 on 2020-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_sub_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_name',
            field=models.CharField(max_length=20, verbose_name='子名称'),
        ),
    ]
