# Generated by Django 3.0.5 on 2020-04-15 13:47

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200415_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='文章分类所属的分类名称', max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_name',
            field=models.CharField(help_text='url地址传参的字符串(英文)', max_length=20, verbose_name='子名称'),
        ),
        migrations.AlterField(
            model_name='post',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='文章的创建时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='文章分类。必填，可选多个', to='blog.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='click_num',
            field=models.PositiveIntegerField(default=0, help_text='文章的点击量，不需要设置', verbose_name='访问量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='文章内容，必填', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='文章标题。必填，不超过30个字符', max_length=30, unique=True, verbose_name='标题'),
        ),
    ]
