# Generated by Django 3.0.5 on 2020-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200415_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='', help_text='文章摘要，选填，最多不超过300个字符', max_length=300, verbose_name='文章摘要'),
        ),
    ]
