# Generated by Django 3.0.5 on 2020-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(default='', help_text='文章摘要，选填，最多不超过300个字符', max_length=300, verbose_name='文章摘要'),
        ),
    ]
