# Generated by Django 3.0.5 on 2020-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200415_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True, default='', help_text='文章摘要，选填，最多不超过300个字符', max_length=300, null=True, verbose_name='文章摘要'),
        ),
    ]
