# Generated by Django 3.0.5 on 2020-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200415_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', help_text='文章封面，必填，建议图片尺寸最好为770*(377-399)', max_length=200, upload_to='post/', verbose_name='文章封面'),
            preserve_default=False,
        ),
    ]
