# Generated by Django 3.0.5 on 2020-04-17 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='文章的创建时间', verbose_name='添加时间'),
        ),
    ]
