# Generated by Django 2.1.4 on 2020-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200417_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='文章封面，必填，建议图片尺寸最好为770*(377-399)', max_length=200, upload_to='post/', verbose_name='文章封面'),
        ),
    ]
