# Generated by Django 3.0.5 on 2020-04-17 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='项目名')),
                ('image', models.ImageField(upload_to='project/', verbose_name='项目图片')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='项目URL地址')),
                ('desc', models.CharField(max_length=200, verbose_name='项目说明')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
