# Generated by Django 3.0.5 on 2020-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='图片比例大小为宽高比1.33（最好为350*262）', upload_to='project/', verbose_name='项目图片'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=30, unique=True, verbose_name='项目名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(help_text='项目URL地址，以/开始的地址', max_length=100, unique=True, verbose_name='项目URL地址'),
        ),
    ]
