# Generated by Django 3.0.5 on 2020-04-17 08:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200417_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='图片比例大小为宽高比1.33（最好为350*262）', upload_to='project/', verbose_name='项目图片'),
        ),
    ]
