# Generated by Django 2.1.4 on 2020-04-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200417_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yzb',
            fields=[
                ('num', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='考生编号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('code', models.CharField(max_length=8, verbose_name='专业代码')),
                ('code_name', models.CharField(max_length=20, verbose_name='专业名称')),
                ('chushi', models.PositiveSmallIntegerField(verbose_name='初试分数')),
                ('fushi', models.PositiveSmallIntegerField(verbose_name='复试分数')),
                ('mark', models.CharField(default='', max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '燕大研招办',
                'verbose_name_plural': '燕大研招办',
            },
        ),
    ]
