# Generated by Django 2.1.4 on 2020-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_yzb_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='yzb',
            name='is_tj',
            field=models.BooleanField(choices=[('0', '一志愿'), ('1', '调剂')], default=False, verbose_name='是否调剂'),
        ),
    ]
