# Generated by Django 2.1.4 on 2020-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_yzb_is_tj'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show',
            field=models.BooleanField(choices=[(0, '不显示'), (1, '显示')], default=0, verbose_name='是否显示'),
        ),
    ]
