# Generated by Django 3.0.5 on 2020-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(default='', help_text='必填，图片标题', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='alt',
            field=models.CharField(blank=True, help_text='选填，当图片无法显示时，显示的文字信息', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(help_text='必填，上传图片', max_length=200, upload_to='gallery/', verbose_name='图片'),
        ),
    ]
