# Generated by Django 3.0.5 on 2020-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200415_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='alt',
            field=models.CharField(blank=True, help_text='选填，当图片无法显示时，显示的文字信息', max_length=20, null=True, verbose_name='图片说明'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(help_text='必填，图片标题', max_length=20, verbose_name='图片标题'),
        ),
    ]
