# Generated by Django 3.0.5 on 2020-04-17 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200415_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
